version: '3'

services:
  node:
    container_name: taskriser
    image: node:12
    ports:
      - '9005:8080'
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    command: >
      bash -c "npm install && npm run serve"
      
      
      
      
