version: '3'

services:
  node:
    container_name: teste-fbinfo-front
    build: .
    restart: unless-stopped
    ports:
      - '9005:8080'
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    command: 'npm run serve'